name: windflow-light 
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - mpi4py
  - cartopy
  - voila
  - netcdf4
  - xarray
  - dask
  - scipy
  - pip
  - zarr
  - opencv
  - pyresample
  - pyproj
  - pytorch
  - torchvision
  - botocore
  - boto3
